services:
  - type: web
    name: sentinel-nrmrag-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: IS_PRODUCTION
        value: "True"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: KAGGLE_USERNAME
        value: "" # PLEASE SET IN RENDER DASHBOARD
      - key: KAGGLE_KEY
        value: "" # PLEASE SET IN RENDER DASHBOARD
